### ISSUE TITLE
addhist country does not allow for commas or special characters

### ISSUE THREAD

**Issue by cs2113-bot-feedback** [CS2113-AY1819S1-T12-2/main#163]
![image](https://user-images.githubusercontent.com/39690145/47907298-e9f6f680-dec5-11e8-88a8-509bb592b102.png)

this makes it unable to add a sub name to the country, ie province or state.

<hr>

**Reported by:** @bearperson1
**Severity:** `Medium`

<sub>[original: nusCS2113-AY1819S1/pe-1#414]</sub>

**Comment by xShaivan** [comment]
Unable to produce this bug on our team's end, however I realised that my regex did not allow whitespaces and hence has been resolved. Thanks for the feedback.
